/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RLuWvdDONww
 */
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-900">
      <main className="w-full max-w-md mx-auto bg-white dark:bg-gray-800 rounded-xl shadow-md overflow-hidden p-6 space-y-4">
        <h1 className="text-2xl font-bold text-center dark:text-white">Todo App</h1>
        <div className="space-y-4">
          <Card>
            <CardContent className="flex flex-row items-start gap-2 p-4">
              <Checkbox id="task0" />
              <div className="space-y-1 leading-none flex-grow">
                <Label className="text-lg font-semibold dark:text-gray-200" htmlFor="task0">
                  New Task
                </Label>
                <p className="text-sm text-gray-500 dark:text-gray-400">This is a new task.</p>
              </div>
              <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex flex-row items-start gap-2 p-4">
              <Checkbox defaultChecked id="task1" />
              <div className="space-y-1 leading-none flex-grow">
                <Label className="text-lg font-semibold dark:text-gray-200" htmlFor="task1">
                  Morning Run
                </Label>
                <p className="text-sm text-gray-500 dark:text-gray-400">Complete a 5km run.</p>
              </div>
              <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex flex-row items-start gap-2 p-4">
              <Checkbox id="task2" />
              <div className="space-y-1 leading-none flex-grow">
                <Label className="text-lg font-semibold dark:text-gray-200" htmlFor="task2">
                  Read a Book
                </Label>
                <p className="text-sm text-gray-500 dark:text-gray-400">Read at least 50 pages of a book.</p>
              </div>
              <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="flex flex-row items-start gap-2 p-4">
              <Checkbox id="task3" />
              <div className="space-y-1 leading-none flex-grow">
                <Label className="text-lg font-semibold dark:text-gray-200" htmlFor="task3">
                  Grocery Shopping
                </Label>
                <p className="text-sm text-gray-500 dark:text-gray-400">Buy groceries for the week.</p>
              </div>
              <Button className="ml-auto h-8 w-8" size="icon" variant="outline">
                <TrashIcon className="h-4 w-4" />
                <span className="sr-only">Delete task</span>
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
